# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "3.0.2" %}

package:
  name: matplotlib-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 4682a2a4e66eed054d78a1eae5936d2174e8c145486db59f12a585aef991fad5
  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]

build:
  number: 1002
  skip: true  # [py<35]

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - python-dateutil
    - freetype
    - msinttypes  # [win]
    - cycler >=0.10
    - nose
    - pyparsing
    - libpng
    - zlib  # [win]
    - tk  # [linux]
    - icu  # [linux]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cycler >=0.10
    - python-dateutil
    - freetype
    - pyparsing
    - libpng
    - tk  # [linux]
    - icu  # [linux]
    - tornado
    - kiwisolver

outputs:
  - name: matplotlib-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - pkg-config  # [not win]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - setuptools
        - numpy >=1.10
        - python-dateutil
        - freetype
        - msinttypes  # [win]
        - cycler >=0.10
        - nose
        - pyparsing
        - libpng
        - zlib  # [win]
        - tk  # [linux]
        - icu  # [linux]
      run:
        - python
        - setuptools
        - {{ pin_compatible('numpy') }}
        - cycler >=0.10
        - python-dateutil
        - freetype
        - pyparsing
        - libpng
        - tk  # [linux]
        - icu  # [linux]
        - tornado
        - kiwisolver

    test:
      imports:
        - matplotlib
        - matplotlib.pyplot
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.ft2font
        - matplotlib.ttconv
        - matplotlib.backends._tkagg  # [not win]
        - mpl_toolkits
        - pylab

  - name: matplotlib
    requirements:
      host:
        - python
        - pyqt  # [not osx]
      run:
        - python
        - pyqt  # [not osx]
        - {{ pin_subpackage('matplotlib-base', exact=True) }}
    test:
      imports:
        - matplotlib

  - name: mpl_sample_data
    script: install-data.sh  # [not win]
    script: install-data.bat  # [win]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('matplotlib-base', exact=True) }}
    test:
      imports:
        - matplotlib.cbook
      commands:
        - python -c "import matplotlib; matplotlib.cbook.get_sample_data('msft.csv', asfileobj=False)"

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
