# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "3.0.1" %}

package:
  name: matplotlib-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 147306a20b2ec29ba5dcc8a8fdada57d5d7eb0aa7e42af984e762d956c97b0d5
  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]

build:
  number: 1001
  skip: true  # [py<35]

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy >=1.10
    - python-dateutil
    - freetype
    - msinttypes  # [win]
    - cycler >=0.10
    - nose
    - pyparsing
    - libpng
    - zlib  # [win]
    - tk  # [linux]
    - icu  # [linux]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cycler >=0.10
    - python-dateutil
    - freetype
    - pyparsing
    - libpng
    - tk  # [linux]
    - icu  # [linux]
    - tornado
    - kiwisolver

outputs:
  - name: matplotlib-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - pkg-config  # [not win]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - setuptools
        - numpy >=1.10
        - python-dateutil
        - freetype
        - msinttypes  # [win]
        - cycler >=0.10
        - nose
        - pyparsing
        - libpng
        - zlib  # [win]
        - tk  # [linux]
        - icu  # [linux]
      run:
        - python
        - setuptools
        - {{ pin_compatible('numpy') }}
        - cycler >=0.10
        - python-dateutil
        - freetype
        - pyparsing
        - libpng
        - tk  # [linux]
        - icu  # [linux]
        - tornado
        - kiwisolver

    test:
      imports:
        - matplotlib
        - matplotlib.pyplot
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.ft2font
        - matplotlib.ttconv
        - matplotlib.backends._tkagg  # [not win]
        - mpl_toolkits
        - pylab

  - name: matplotlib
    requirements:
      host:
        - python
        - pyqt  # [not osx]
      run:
        - {{ pin_subpackage('matplotlib-base', exact=True) }}
        - pyqt  # [not osx]

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
