# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.0.0b4" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 8648dce20b53271720d8c5c439c23c11c220561119242c7fcd14ea10ca2ef3f9

  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]

build:
    number: 0

requirements:
  build:
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.6.*
    - msinttypes  # [win]
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
#    - py2cairo  # [linux and py2k]
    - tornado
    - libpng >=1.6.21,<1.7
    - zlib 1.2.*  # [win]
    - pyqt  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 56.*  # [linux]
  run:
    - python
    - numpy x.x
    - cycler >=0.10
    - python-dateutil
    - freetype 2.6.*
    - pytz
    - pyparsing
#    - py2cairo  # [linux and py2k]
    - libpng >=1.6.21,<1.7
    - pyqt  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 56.*  # [linux]
    - setuptools

test:
    imports:
        - matplotlib
        - matplotlib.pyplot
        - mpl_toolkits

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
