# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "3.1.0rc1" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: a2b78bb3c4988ff8039cf2abba644a7fb60a2a161c4a62ab418a8081bc83084a
  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]

build:
    number: 0
    skip: true  # [py2k]

requirements:
  build:
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - python-dateutil
    - freetype
    - msinttypes  # [win]
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
    - libpng
    - zlib  # [win]
    - pyqt  # [not osx]
    - tk  # [linux]
    - icu  # [linux]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cycler >=0.10
    - python-dateutil
    - freetype
    - pytz
    - pyparsing
    - libpng
    - pyqt  # [not osx]
    - tk  # [linux]
    - icu  # [linux]
    - tornado
    - kiwisolver

test:
  imports:
    - matplotlib
    - matplotlib.pyplot
    - matplotlib._image
    - matplotlib._path
    - matplotlib._png
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.ft2font
    - matplotlib.ttconv
    - mpl_toolkits
    - pylab

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
