# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "1.5.2" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: c334c5dccda790423e1e6ebc5a9a442aa2423894cfea08e62c5fd0116e40d9ae
  patches:
    # Find Tcl and libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]

build:
    number: 6

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.6.*
    - msinttypes  # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
    - tornado
    - libpng >=1.6.21,<1.7
    - zlib 1.2.*  # [win]
    - pyqt  # [win]
    - tk 8.5.*  # [linux]
    - pyqt  # [win]
    - tk 8.5.*
  run:
    - python
    - numpy x.x
    - cycler
    - python-dateutil
    - freetype 2.6.*
    - pytz
    - pyparsing
    - libpng >=1.6.21,<1.7
    - pyqt  # [win]
    - tk 8.5.*
    - functools32  # [py2k]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
