# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.2.5" %}

package:
  name: matplotlib-base
  version: {{ version }}

source:
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 75e9de4e4e47ae4cb23393e9df9431424d5034da77771d598ff14363d6a51dd1
  patches:
    # Find libpng on Windows.
    - patches/setupext.patch  # [win]
    # A patch to make Qt the default backend.
    - patches/cfg_qt5agg.patch  # [not osx]
    # Removes framework check from osx backend (seems unneeded)
    - patches/osx-frame.patch  # [osx]

build:
  number: 3

outputs:
  - name: matplotlib-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      build:
        - pkg-config  # [not win]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - backports.functools_lru_cache  # [py2k]
        - numpy
        - python-dateutil
        - freetype
        - msinttypes  # [win]
        - cycler >=0.10
        - nose
        - pyparsing
        - pytz
        - libpng
        - zlib  # [win]
        - tk  # [linux]
        - functools32  # [py2k]
        - subprocess32  # [py2k and unix]
        - icu  # [linux]
      run:
        - python
        - setuptools
        - {{ pin_compatible('numpy') }}
        - backports.functools_lru_cache  # [py2k]
        - cycler >=0.10
        - python-dateutil
        - freetype
        - pytz
        - pyparsing
        - libpng
        - tk  # [linux]
        - functools32  # [py2k]
        - subprocess32  # [py2k and unix]
        - icu  # [linux]
        - tornado
        - kiwisolver
    test:
      imports:
        - matplotlib
        - matplotlib.pyplot
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.ft2font
        - matplotlib.ttconv
        - matplotlib.backends._tkagg  # [not win]
        - mpl_toolkits
        - pylab

  - name: matplotlib
    build:
    requirements:
      run:
        - pyqt  # [not osx and not aarch64 and not ppc64le]
        - {{ pin_subpackage('matplotlib-base', max_pin="x.x.x.x") }}
    test:
      imports:
        - matplotlib

  - name: mpl_sample_data
    script: install-data.sh  # [not win]
    script: install-data.bat  # [win]
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        # match major/minor version, but allow noarch
        - {{ pin_subpackage('matplotlib-base', max_pin="x.x") }}
    test:
      imports:
        - matplotlib.cbook
      commands:
        - python -c "import matplotlib; matplotlib.cbook.get_sample_data('msft.csv', asfileobj=False)"

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
