# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "1.5.2rc1" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 73b01a78aeb701dc04b5ca5767f7a8aac82b3b4a3575369b0a9e3145c640e345

  patches:
    # Find Tcl and libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch  # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]
    # Patches setupext to look in PREFIX for the tcl/tk headers.
    - osx-tk.patch  # [osx]

build:
    number: 1

requirements:
  build:
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.6*
    - msinttypes  # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
#    - py2cairo  # [linux and py2k]
    - tornado
    - libpng 1.6*
    - zlib 1.2*  # [win]
    - pyqt  # [not osx]
    - tk  # [linux]
  run:
    - python
    - numpy x.x
    - cycler
    - python-dateutil
    - freetype 2.6*
    - pytz
    - pyparsing
#    - py2cairo  # [linux and py2k]
    - libpng 1.6*
    - pyqt  # [not osx]
    - tk  # [linux]
    - functools32  # [py2k]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
