# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.

{% set version = "2.0.0" %}

package:
  name: matplotlib
  version: {{ version }}

source:
  fn: matplotlib-{{ version }}.tar.gz
  url: https://github.com/matplotlib/matplotlib/archive/v{{ version }}.tar.gz
  sha256: 966a0807bc961726a68e5b60b6e97c91eed6ba20e0d50dfd699a8f854b2d7370
  patches:
    # Find libpng on Windows.
    - setupext.patch  # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt5agg.patch  # [not osx]
    # Removes framework check from osx backend (seems unneeded)
    - osx-frame.patch  # [osx]

build:
  number: 3

requirements:
  build:
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.7|2.7.*
    - msinttypes  # [win]
    - cycler >=0.10
    - nose
    - pyparsing
    - pytz
    #- py2cairo  # [linux and py2k]
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*  # [win]
    - pyqt 5.6.*  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 58.*  # [linux]
  run:
    - python
    - setuptools
    - numpy x.x
    - cycler >=0.10
    - python-dateutil
    - freetype 2.7|2.7.*
    - pytz
    - pyparsing
    #- py2cairo  # [linux and py2k]
    - libpng >=1.6.28,<1.7
    - pyqt 5.6.*  # [not osx]
    - tk 8.5.*  # [linux]
    - functools32  # [py2k]
    - subprocess32  # [py2k and unix]
    - icu 58.*  # [linux]
    - tornado

test:
  imports:
    - matplotlib
    - matplotlib.pyplot
    - matplotlib._cntr
    - matplotlib._delaunay
    - matplotlib._image
    - matplotlib._path
    - matplotlib._png
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.ft2font
    - matplotlib.ttconv
    - matplotlib.backends._tkagg  # [not win]
    - mpl_toolkits
    - pylab
  commands:
    - conda inspect linkages -p $PREFIX matplotlib  # [not win]
    - conda inspect objects -p $PREFIX matplotlib  # [osx]

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Publication quality figures in Python
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html

extra:
  recipe-maintainers:
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
    - dopplershift
