bot:
  abi_migration_branches:
  - testing
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux: azure
  linux_aarch64: default
  linux_ppc64le: default
  osx: azure
  win: azure
conda_build:
  pkg_format: '2'
test: native_and_emulated
