appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: redV8EPEfpaRtRE8u8jAXiR/Zoxu9TCN6D8ufhSFrkNSZ8hNJRtHzN/RJsY3b/tNr7xCegaP3xk+kfaN3c8C0lW/Y+7ayCI38VVibLNsIvzY8ev2UPHb6oLNkp9mpuXk+5c1CA7aGsvYD6EvNMe1nCdUnopSgDNi5qYWjPFQte2gavgVMJqU4FGiQ1upcW9LGyBepbGauqUAYPkJev4BTMWigSvAYanJdT9rZMdO/z3gjBEcmFQI71JgBC7qyiKLVtIpdhUKlHNZxyIWQItgpm6DJOUS0WJniWZxtmaRfYTzFCdR7lRqBMG6deQiSJxM/dubf3uFVDNPOh7+YA3NQcFMoKm/hVdVEQZBNErqUVlkN2evlGizZZiJAkWTX0u+kaAAxe+fKRvdugL2FWuS6Mt/P/l6vBJLRMBiTSidOplqYwIgufNl9Zuwcl9/9Jq37ec3of7Ul0Sm6BBOrbnhEnsZc8v6raJ7xejd1futEKKvOSIJX/TPfTu5fUDwlcZDM9W2MRLqVR2uOfSIDY8izMvpWXRn8T+F59ZVPsH232evd+zlVNSVvwzKrTGyCSEqz+zXYGtRIjSReSiHXnlFfDtTXDiV6D+4tCKZhaaa3HW27iLwqpBRK7pldXyLWPYmdBybZksKj2wgL8fm3S0dEG/b68bVzUxW54RHaYLoR8A=}
provider:
  osx: azure
  linux: azure
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
