travis:
  secure:
    BINSTAR_TOKEN: Gxec2n1/iEz3PtkzKYmRC630hCK5hg6qnEtYjBJKkAF97119AlSZZa/8J1bMoVOVifIup2+Gj6NQt3X2Dv+akj874AHJ6oFeyhvgqz6F6fICNr8nLc7g2GYdCMg/j3qx3/eVPSFk9r9LTiOFoB/T0+9n9j5XgdNazLtgvRQOcWq09D6B+2mjl2w+qWEQYJH+DIdIAdQpuPyjhVTUV/F8oUi/KOMruLcUS2VAJ7mGvgF4G+Iu0paAgGa3hbez2wmAqi5BFE2F7UzGVdVaIHwsvUDkZVH1NF+9LgjZX2Vt9FzjdcZZhWi81t/5PyWNL5EL+QTiZA8YghseHUxM81uiT7WklUypHLlB4XjWWR5cCU23joLjQXPWI6YiNn++D5xGDMtNvLFkqGr11RTWvjWYVUudyjW3wcz1HAWOPMZC7AK+2UIaUL8rNBYUd5G7WImd3KatDZNmIcWSW95RCKNafnCtZinJ4/K9yamkMfzPjqn+gu2EIMJN8lp1r8fje6cXZ6w5QXfw1+awUtVFwu503/cSFzQ2Vus6S12Y9pQ9sgo7OW6hKWqnijGRE/UGBayTVXAJeIYV4Z3izHgvGRRKiuIdKmmemEB+HS0vobZE4K2GOhBiVYsAqrthdRFz9YOFSJbaiGAM8EjzTzYFkaT7dQ2PMf5Bwft/1E/fi6iReNc=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
