bot:
  abi_migration_branches:
  - testing
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux: azure
  osx: azure
  win: azure
test_on_native_only: true
conda_build:
  pkg_format: '2'
