build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux: azure, linux_aarch64: default, linux_ppc64le: default, osx: azure,
  win: azure}
bot:
  abi_migration_branches:
  - testing
  - v2.2.x
conda_build:
  pkg_format: '2'
test: native_and_emulated
