# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      osx_numpy1.14python3.6.____cpython:
        CONFIG: osx_numpy1.14python3.6.____cpython
        UPLOAD_PACKAGES: True
      osx_numpy1.14python3.7.____cpython:
        CONFIG: osx_numpy1.14python3.7.____cpython
        UPLOAD_PACKAGES: True
      osx_numpy1.14python3.8.____cpython:
        CONFIG: osx_numpy1.14python3.8.____cpython
        UPLOAD_PACKAGES: True
      osx_numpy1.18python3.6.____73_pypy:
        CONFIG: osx_numpy1.18python3.6.____73_pypy
        UPLOAD_PACKAGES: True

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)